repos: 
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.1
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.31.1 # grab latest tag from GitHub
    hooks:
      - id: djlint-django
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
  - repo: local
      hooks:
        - id: pre-commit-django-migrations
          name: Check django migrations
          entry: docker-compose exec -T wagtail python manage.py makemigrations --check --dry-run
          language: system
          types: [python]
          stages: [push]
          pass_filenames: false