# Generated by Django 5.1.5 on 2025-01-31 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_alter_homepage_options_homepage_cta_link_a_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="custom_title",
            field=models.CharField(default=(), max_length=250, verbose_name="Titre"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="homepage",
            name="subtitle",
            field=models.CharField(max_length=250, verbose_name="Sous-titre"),
        ),
    ]
