# Generated by Django 5.1.5 on 2025-01-31 10:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_homepage_custom_title_alter_homepage_subtitle"),
    ]

    operations = [
        migrations.RenameField(
            model_name="homepage",
            old_name="image",
            new_name="photo",
        ),
    ]
