# Generated by Django 5.1.5 on 2025-01-31 15:47

import core.blocks
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page Contact",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="StandardPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("rich_text", 0),
                            ("quote", 4),
                            ("carousel", 5),
                            ("image", 8),
                            ("video", 11),
                            ("rotating", 15),
                        ],
                        block_lookup={
                            0: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "h2",
                                        "h3",
                                        "h4",
                                        "bold",
                                        "hr",
                                        "italic",
                                        "link",
                                        "ol",
                                        "ul",
                                    ],
                                    "group": "Blocs de texte",
                                    "label": "Texte riche",
                                },
                            ),
                            1: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {
                                    "help_text": "Les guillemets seront ajoutés automatiquement.",
                                    "label": "Citation",
                                },
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Auteur", "required": False},
                            ),
                            3: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"label": "Image de profil", "required": False},
                            ),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [[("quote", 1), ("author", 2), ("image", 3)]],
                                {"group": "Blocs éditoriaux", "label": "Citation"},
                            ),
                            5: (
                                "wagtail.blocks.ListBlock",
                                (core.blocks.ImageBlock,),
                                {
                                    "group": "Médias",
                                    "icon": "image",
                                    "label": "Carousel",
                                },
                            ),
                            6: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            7: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 6), ("caption", 7)]],
                                {"group": "Médias", "label": "Image"},
                            ),
                            9: (
                                "core.blocks.EmbedBlockEnhanced",
                                (),
                                {"label": "Lien de la vidéo"},
                            ),
                            10: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Légende", "required": False},
                            ),
                            11: (
                                "wagtail.blocks.StructBlock",
                                [[("embed", 9), ("caption", 10)]],
                                {"group": "Médias", "label": "Video"},
                            ),
                            12: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Texte fixe"},
                            ),
                            13: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Texte flottant"},
                            ),
                            14: (
                                "wagtail.blocks.ListBlock",
                                (13,),
                                {"max_num": 3, "min_num": 3},
                            ),
                            15: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 12), ("items", 14)]],
                                {
                                    "group": "Blocs éditoriaux",
                                    "label": "Roulette de textes",
                                },
                            ),
                        },
                        verbose_name="Corps de page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page standard",
            },
            bases=("wagtailcore.page",),
        ),
    ]
