# Generated by Django 5.1.5 on 2025-02-11 15:07

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_formpage_formfield_delete_contactmepage"),
    ]

    operations = [
        migrations.CreateModel(
            name="FooterSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", wagtail.fields.RichTextField(verbose_name="Texte du footer")),
                ("linkedin", models.URLField(verbose_name="Linkedin")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Adresse mail"),
                ),
            ],
            options={
                "verbose_name": "Pied de page",
            },
        ),
        migrations.CreateModel(
            name="MenusSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "main_menu",
                    wagtail.fields.StreamField(
                        [("menu_item", 2)],
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"label": "Titre"}),
                            1: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"label": "Lien vers la page"},
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("url", 1)]],
                                {"label": "Item de niveau 1"},
                            ),
                        },
                        verbose_name="Menu principal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu principal",
            },
        ),
    ]
