# Generated by Django 5.1.5 on 2025-02-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_menussettings_button"),
    ]

    operations = [
        migrations.AddField(
            model_name="menussettings",
            name="button_title",
            field=models.CharField(
                default=(), max_length=25, verbose_name="Texte du bouton principal"
            ),
            preserve_default=False,
        ),
    ]
